services:
  - type: web
    name: med-order-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci && npm run build
    startCommand: node dist/main.js
    autoDeploy: true
    healthCheckPath: /api/docs
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false # Set this in Render to your existing Prisma Postgres connection string
      - key: JWT_SECRET
        sync: false
      - key: AUTH0_ISSUER_BASE_URL
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ADMIN_EMAILS
        sync: false
      - key: CORS_ORIGIN
        sync: false
    postDeployCommand: npx prisma migrate deploy && npx ts-node prisma/seed.ts

